// <auto-generated />
using System;
using LABOGRA.Services.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LABOGRA.Migrations
{
    [DbContext(typeof(LabDbContext))]
    [Migration("20250508125939_ApplyRefValueStructureAndData")]
    partial class ApplyRefValueStructureAndData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("LABOGRA.Models.LabOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReferringPhysicianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReferringPhysicianId");

                    b.ToTable("LabOrders");
                });

            modelBuilder.Entity("LABOGRA.Models.LabOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceRange")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultUnit")
                        .HasColumnType("TEXT");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LabOrderId");

                    b.HasIndex("TestId");

                    b.ToTable("LabOrderItems");
                });

            modelBuilder.Entity("LABOGRA.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgeValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalRecordNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferringPhysicianId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegistrationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReferringPhysicianId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("LABOGRA.Models.ReferringPhysician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReferringPhysicians");
                });

            modelBuilder.Entity("LABOGRA.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "Hb",
                            Name = "Hemoglobin"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "FBG",
                            Name = "Fasting Blood Glucose"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "2hPPG",
                            Name = "Two-Hour Postprandial Glucose"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "RBG",
                            Name = "Random Blood Glucose"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "HbA1c",
                            Name = "Glycated Hemoglobin"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "Cr",
                            Name = "Serum Creatinine"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "Urea",
                            Name = "Blood Urea Nitrogen"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "UA",
                            Name = "Uric Acid"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "Na",
                            Name = "Sodium"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "K",
                            Name = "Potassium"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "Cl",
                            Name = "Chloride"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "Ca²⁺",
                            Name = "Ionized Calcium"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "Ca",
                            Name = "Total Calcium"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "TP",
                            Name = "Total Protein"
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "Alb",
                            Name = "Albumin"
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "TBil",
                            Name = "Total Bilirubin"
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "DBil",
                            Name = "Direct Bilirubin"
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "ALT",
                            Name = "Alanine Transaminase"
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "AST",
                            Name = "Aspartate Transaminase"
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "ALP",
                            Name = "Alkaline Phosphatase"
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "TC",
                            Name = "Total Cholesterol"
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "TG",
                            Name = "Triglycerides"
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "HDL",
                            Name = "High-Density Lipoprotein Cholesterol"
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "LDL",
                            Name = "Low-Density Lipoprotein Cholesterol"
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "TSH",
                            Name = "Thyroid Stimulating Hormone"
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "Free T3",
                            Name = "Free Triiodothyronine"
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "Free T4",
                            Name = "Free Thyroxine"
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "PRL",
                            Name = "Prolactin"
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "TT",
                            Name = "Total Testosterone"
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "E2",
                            Name = "Estradiol"
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "LH",
                            Name = "Luteinizing Hormone"
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "FSH",
                            Name = "Follicle-Stimulating Hormone"
                        },
                        new
                        {
                            Id = 33,
                            Abbreviation = "Prog",
                            Name = "Progesterone"
                        },
                        new
                        {
                            Id = 34,
                            Abbreviation = "ESR",
                            Name = "Erythrocyte Sedimentation Rate"
                        },
                        new
                        {
                            Id = 35,
                            Abbreviation = "CRP",
                            Name = "C-Reactive Protein"
                        },
                        new
                        {
                            Id = 36,
                            Abbreviation = "Vit D",
                            Name = "Vitamin D (25-OH)"
                        },
                        new
                        {
                            Id = 37,
                            Abbreviation = "Vit B12",
                            Name = "Vitamin B12"
                        },
                        new
                        {
                            Id = 38,
                            Abbreviation = "Ferritin",
                            Name = "Ferritin"
                        },
                        new
                        {
                            Id = 39,
                            Abbreviation = "Iron",
                            Name = "Serum Iron"
                        },
                        new
                        {
                            Id = 40,
                            Abbreviation = "TIBC",
                            Name = "Total Iron-Binding Capacity"
                        },
                        new
                        {
                            Id = 41,
                            Abbreviation = "LDH",
                            Name = "Lactate Dehydrogenase"
                        },
                        new
                        {
                            Id = 42,
                            Abbreviation = "CK",
                            Name = "Creatine Kinase"
                        },
                        new
                        {
                            Id = 43,
                            Abbreviation = "AMY",
                            Name = "Amylase"
                        },
                        new
                        {
                            Id = 44,
                            Abbreviation = "LIP",
                            Name = "Lipase"
                        },
                        new
                        {
                            Id = 45,
                            Abbreviation = "TnI",
                            Name = "Troponin I"
                        },
                        new
                        {
                            Id = 46,
                            Abbreviation = "D-Dimer",
                            Name = "D-Dimer"
                        },
                        new
                        {
                            Id = 47,
                            Abbreviation = "PSA",
                            Name = "Prostate-Specific Antigen"
                        },
                        new
                        {
                            Id = 48,
                            Abbreviation = "Anti-CCP",
                            Name = "Anti-Cyclic Citrullinated Peptide Antibody"
                        },
                        new
                        {
                            Id = 49,
                            Abbreviation = "ANA",
                            Name = "Antinuclear Antibody"
                        },
                        new
                        {
                            Id = 50,
                            Abbreviation = "RF",
                            Name = "Rheumatoid Factor"
                        });
                });

            modelBuilder.Entity("LABOGRA.Models.TestReferenceValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GenderSpecific")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("TestReferenceValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenderSpecific = "Male",
                            ReferenceText = "13.5 – 17.5",
                            TestId = 1,
                            Unit = "g/dL"
                        },
                        new
                        {
                            Id = 2,
                            GenderSpecific = "Female",
                            ReferenceText = "12.0 – 15.5",
                            TestId = 1,
                            Unit = "g/dL"
                        },
                        new
                        {
                            Id = 3,
                            GenderSpecific = "Any",
                            ReferenceText = "70 – 100",
                            TestId = 2,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 4,
                            GenderSpecific = "Any",
                            ReferenceText = "< 140",
                            TestId = 3,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 5,
                            GenderSpecific = "Any",
                            ReferenceText = "< 200",
                            TestId = 4,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 6,
                            GenderSpecific = "Any",
                            ReferenceText = "4.0 – 5.6",
                            TestId = 5,
                            Unit = "%"
                        },
                        new
                        {
                            Id = 7,
                            GenderSpecific = "Male",
                            ReferenceText = "0.7 – 1.3",
                            TestId = 6,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 8,
                            GenderSpecific = "Female",
                            ReferenceText = "0.5 – 1.1",
                            TestId = 6,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 9,
                            GenderSpecific = "Any",
                            ReferenceText = "7 – 20",
                            TestId = 7,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 10,
                            GenderSpecific = "Any",
                            ReferenceText = "2.4 – 7.0",
                            TestId = 8,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 11,
                            GenderSpecific = "Any",
                            ReferenceText = "135 – 145",
                            TestId = 9,
                            Unit = "mmol/L"
                        },
                        new
                        {
                            Id = 12,
                            GenderSpecific = "Any",
                            ReferenceText = "3.5 – 5.0",
                            TestId = 10,
                            Unit = "mmol/L"
                        },
                        new
                        {
                            Id = 13,
                            GenderSpecific = "Any",
                            ReferenceText = "98 – 106",
                            TestId = 11,
                            Unit = "mmol/L"
                        },
                        new
                        {
                            Id = 14,
                            GenderSpecific = "Any",
                            ReferenceText = "1.12 – 1.32",
                            TestId = 12,
                            Unit = "mmol/L"
                        },
                        new
                        {
                            Id = 15,
                            GenderSpecific = "Any",
                            ReferenceText = "8.5 – 10.2",
                            TestId = 13,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 16,
                            GenderSpecific = "Any",
                            ReferenceText = "6.0 – 8.3",
                            TestId = 14,
                            Unit = "g/dL"
                        },
                        new
                        {
                            Id = 17,
                            GenderSpecific = "Any",
                            ReferenceText = "3.5 – 5.0",
                            TestId = 15,
                            Unit = "g/dL"
                        },
                        new
                        {
                            Id = 18,
                            GenderSpecific = "Any",
                            ReferenceText = "0.1 – 1.2",
                            TestId = 16,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 19,
                            GenderSpecific = "Any",
                            ReferenceText = "0.0 – 0.3",
                            TestId = 17,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 20,
                            GenderSpecific = "Any",
                            ReferenceText = "7 – 56",
                            TestId = 18,
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 21,
                            GenderSpecific = "Any",
                            ReferenceText = "10 – 40",
                            TestId = 19,
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 22,
                            GenderSpecific = "Any",
                            ReferenceText = "44 – 147",
                            TestId = 20,
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 23,
                            GenderSpecific = "Any",
                            ReferenceText = "< 200",
                            TestId = 21,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 24,
                            GenderSpecific = "Any",
                            ReferenceText = "< 150",
                            TestId = 22,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 25,
                            GenderSpecific = "Any",
                            ReferenceText = "> 60",
                            TestId = 23,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 26,
                            GenderSpecific = "Any",
                            ReferenceText = "< 100",
                            TestId = 24,
                            Unit = "mg/dL"
                        },
                        new
                        {
                            Id = 27,
                            GenderSpecific = "Any",
                            ReferenceText = "0.5 – 4.0",
                            TestId = 25,
                            Unit = "mIU/L"
                        },
                        new
                        {
                            Id = 28,
                            GenderSpecific = "Any",
                            ReferenceText = "2.3 – 4.2",
                            TestId = 26,
                            Unit = "pg/mL"
                        },
                        new
                        {
                            Id = 29,
                            GenderSpecific = "Any",
                            ReferenceText = "0.8 – 1.8",
                            TestId = 27,
                            Unit = "ng/dL"
                        },
                        new
                        {
                            Id = 30,
                            GenderSpecific = "Any",
                            ReferenceText = "4.0 – 23.0",
                            TestId = 28,
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 31,
                            GenderSpecific = "Any",
                            ReferenceText = "300 – 1,000",
                            TestId = 29,
                            Unit = "ng/dL"
                        },
                        new
                        {
                            Id = 32,
                            GenderSpecific = "Any",
                            ReferenceText = "20 – 350",
                            TestId = 30,
                            Unit = "pg/mL"
                        },
                        new
                        {
                            Id = 33,
                            GenderSpecific = "Any",
                            ReferenceText = "1.24 – 7.8",
                            TestId = 31,
                            Unit = "IU/L"
                        },
                        new
                        {
                            Id = 34,
                            GenderSpecific = "Any",
                            ReferenceText = "1.5 – 12.4",
                            TestId = 32,
                            Unit = "IU/L"
                        },
                        new
                        {
                            Id = 35,
                            GenderSpecific = "Any",
                            ReferenceText = "0.1 – 25.0",
                            TestId = 33,
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 36,
                            GenderSpecific = "Male",
                            ReferenceText = "< 15",
                            TestId = 34,
                            Unit = "mm/hr"
                        },
                        new
                        {
                            Id = 37,
                            GenderSpecific = "Female",
                            ReferenceText = "< 20",
                            TestId = 34,
                            Unit = "mm/hr"
                        },
                        new
                        {
                            Id = 38,
                            GenderSpecific = "Any",
                            ReferenceText = "< 3.0",
                            TestId = 35,
                            Unit = "mg/L"
                        },
                        new
                        {
                            Id = 39,
                            GenderSpecific = "Any",
                            ReferenceText = "20 – 50",
                            TestId = 36,
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 40,
                            GenderSpecific = "Any",
                            ReferenceText = "200 – 900",
                            TestId = 37,
                            Unit = "pg/mL"
                        },
                        new
                        {
                            Id = 41,
                            GenderSpecific = "Male",
                            ReferenceText = "24 – 336",
                            TestId = 38,
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 42,
                            GenderSpecific = "Female",
                            ReferenceText = "11 – 307",
                            TestId = 38,
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 43,
                            GenderSpecific = "Any",
                            ReferenceText = "60 – 170",
                            TestId = 39,
                            Unit = "µg/dL"
                        },
                        new
                        {
                            Id = 44,
                            GenderSpecific = "Any",
                            ReferenceText = "240 – 450",
                            TestId = 40,
                            Unit = "µg/dL"
                        },
                        new
                        {
                            Id = 45,
                            GenderSpecific = "Any",
                            ReferenceText = "140 – 280",
                            TestId = 41,
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 46,
                            GenderSpecific = "Male",
                            ReferenceText = "52 – 336",
                            TestId = 42,
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 47,
                            GenderSpecific = "Female",
                            ReferenceText = "38 – 176",
                            TestId = 42,
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 48,
                            GenderSpecific = "Any",
                            ReferenceText = "23 – 85",
                            TestId = 43,
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 49,
                            GenderSpecific = "Any",
                            ReferenceText = "0 – 160",
                            TestId = 44,
                            Unit = "U/L"
                        },
                        new
                        {
                            Id = 50,
                            GenderSpecific = "Any",
                            ReferenceText = "< 0.04",
                            TestId = 45,
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 51,
                            GenderSpecific = "Any",
                            ReferenceText = "< 0.5",
                            TestId = 46,
                            Unit = "µg/mL FEU"
                        },
                        new
                        {
                            Id = 52,
                            GenderSpecific = "Any",
                            ReferenceText = "< 4.0",
                            TestId = 47,
                            Unit = "ng/mL"
                        },
                        new
                        {
                            Id = 53,
                            GenderSpecific = "Any",
                            ReferenceText = "< 20",
                            TestId = 48,
                            Unit = "U/mL"
                        },
                        new
                        {
                            Id = 54,
                            GenderSpecific = "Any",
                            ReferenceText = "Negative at < 1:40",
                            TestId = 49,
                            Unit = "Titer"
                        },
                        new
                        {
                            Id = 55,
                            GenderSpecific = "Any",
                            ReferenceText = "< 15",
                            TestId = 50,
                            Unit = "IU/mL"
                        });
                });

            modelBuilder.Entity("LABOGRA.Models.LabOrder", b =>
                {
                    b.HasOne("LABOGRA.Models.Patient", "Patient")
                        .WithMany("LabOrders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LABOGRA.Models.ReferringPhysician", "ReferringPhysician")
                        .WithMany()
                        .HasForeignKey("ReferringPhysicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("ReferringPhysician");
                });

            modelBuilder.Entity("LABOGRA.Models.LabOrderItem", b =>
                {
                    b.HasOne("LABOGRA.Models.LabOrder", "LabOrder")
                        .WithMany("Items")
                        .HasForeignKey("LabOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LABOGRA.Models.Test", "Test")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabOrder");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("LABOGRA.Models.Patient", b =>
                {
                    b.HasOne("LABOGRA.Models.ReferringPhysician", "ReferringPhysician")
                        .WithMany()
                        .HasForeignKey("ReferringPhysicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReferringPhysician");
                });

            modelBuilder.Entity("LABOGRA.Models.TestReferenceValue", b =>
                {
                    b.HasOne("LABOGRA.Models.Test", "Test")
                        .WithMany("ReferenceValues")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("LABOGRA.Models.LabOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LABOGRA.Models.Patient", b =>
                {
                    b.Navigation("LabOrders");
                });

            modelBuilder.Entity("LABOGRA.Models.Test", b =>
                {
                    b.Navigation("ReferenceValues");
                });
#pragma warning restore 612, 618
        }
    }
}
